### PR TITLE
Build with docker and make

### PR DESCRIPTION
**Pull request by branning**
Add an unattended build method. Platforms that can muster Docker and Make can do:

    make docker-build

### CODE REVIEW

**Comment by mignon-p** [comment]
Hi, could you elaborate on the change to `bld/cmake/ObGeneratePC.cmake`?

I don't really understand CMake and I'm not sure how it's supposed to work, but when I did a `ninja install` on your branch, it now seems to install each of the `.pc` files in two different locations:

```
-- Installing: /opt/plasma/lib/pkgconfig/libPlasmaZeroconf.pc
-- Installing: /pkgconfig/libPlasmaZeroconf.pc
```

I much prefer the new location of `${CMAKE_INSTALL_PREFIX}/lib/pkgconfig` over the old location of `/pkgconfig`.  However, I don't think we need to install it in both places, and I'm unclear where the install to the old location is happening, since it doesn't look like it's happening in the same file that you changed.

**Comment by branning** [comment]
> Hi, could you elaborate on the change to `bld/cmake/ObGeneratePC.cmake`?

The version you tested was double-installing the .pc files. These changes are not needed as long as you specify CMAKE_INSTALL_PREFIX, and there is an example of doing that in the `build` Makefile rule.

This now cleanly installs plasma to `PLASMA_INSTALL`:

    PLASMA_INSTALL=/path/to/plasma make install

**Comment by branning** [comment]
@mignon-p I removed the CMake changes and added some instructions for installing. Does that work for you?

**Comment by mignon-p** [comment]
Looks good to me.  Thanks!

**Pull request merged**
